import React, { useState } from "react";
import { Table, Button, Card, Tag, Typography, Space, Modal } from "antd";
import {
  FileTextOutlined,
  DownloadOutlined,
  BarChartOutlined,
  PieChartOutlined,
  DollarOutlined,
  UserOutlined,
} from "@ant-design/icons";
import Sidebar from "../../components/sidebar/Sidebar";
import "./Report.css";

const { Title } = Typography;

const Reports: React.FC = () => {
  const data = [
    { key: "1", name: "Attendance Summary", category: "Attendance", generatedBy: "Admin", date: "2025-11-01" },
    { key: "2", name: "Payroll Report", category: "Finance", generatedBy: "Finance Head", date: "2025-11-05" },
    { key: "3", name: "Performance Overview", category: "HR", generatedBy: "HR Manager", date: "2025-11-03" },
    { key: "4", name: "Recruitment Summary", category: "Recruitment", generatedBy: "Recruiter", date: "2025-11-07" },
  ];

  const [filteredData, setFilteredData] = useState(data);
  const [selectedCard, setSelectedCard] = useState<string | null>(null);
  const [viewModalData, setViewModalData] = useState<any>(null);

  const handleCardClick = (category: string | null) => {
    setSelectedCard(category);
    setFilteredData(!category ? data : data.filter(item => item.category === category));
  };

  const handleExport = (record: any) => {
    const blob = new Blob([JSON.stringify(record, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${record.name.replace(/ /g, "_")}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const columns = [
    {
      title: "Report Name",
      dataIndex: "name",
      key: "name",
      render: (text: string) => (
        <Space>
          <FileTextOutlined style={{ color: "#3b82f6" }} />
          <span style={{ fontWeight: 500 }}>{text}</span>
        </Space>
      ),
    },
    {
      title: "Category",
      dataIndex: "category",
      key: "category",
      render: (cat: string) => (
        <Tag color={{ HR: "purple", Finance: "green", Recruitment: "geekblue", Attendance: "orange" }[cat] || "blue"}>
          {cat}
        </Tag>
      ),
    },
    { title: "Generated By", dataIndex: "generatedBy", key: "generatedBy" },
    {
      title: "Generated On",
      dataIndex: "date",
      key: "date",
      render: (d: string) =>
        new Date(d).toLocaleDateString("en-GB", {
          day: "2-digit",
          month: "short",
          year: "numeric",
        }),
    },
    {
      title: "Actions",
      key: "actions",
      render: (_: any, record: any) => (
        <Space>
          <Button type="link" icon={<DownloadOutlined />} onClick={() => handleExport(record)}>
            Export
          </Button>
          <Button type="link" icon={<BarChartOutlined />} onClick={() => setViewModalData(record)}>
            View
          </Button>
        </Space>
      ),
    },
  ];

  return (
    <div className="hrms-dashboard-container">
      <Sidebar />

      <div className="hrms-dashboard-main">
        <div className="reports-header">
          <Title level={2}>📊 Reports & Analytics</Title>
          <p>Download, review, and manage all HRMS reports in one place.</p>
        </div>

        {/* SUMMARY CARDS */}
        <div className="reports-summary">
          <Card
            className={`reports-card ${selectedCard === "Attendance" ? "active-card" : ""}`}
            onClick={() => handleCardClick("Attendance")}
          >
            <UserOutlined className="card-icon" />
            <h3>Attendance Reports</h3>
            <p>15</p>
          </Card>

          <Card
            className={`reports-card ${selectedCard === "Finance" ? "active-card" : ""}`}
            onClick={() => handleCardClick("Finance")}
          >
            <DollarOutlined className="card-icon" />
            <h3>Payroll Reports</h3>
            <p>10</p>
          </Card>

          <Card
            className={`reports-card ${selectedCard === "HR" ? "active-card" : ""}`}
            onClick={() => handleCardClick("HR")}
          >
            <PieChartOutlined className="card-icon" />
            <h3>Performance Reports</h3>
            <p>8</p>
          </Card>

          <Card
            className={`reports-card ${selectedCard === "Recruitment" ? "active-card" : ""}`}
            onClick={() => handleCardClick("Recruitment")}
          >
            <FileTextOutlined className="card-icon" />
            <h3>Recruitment Reports</h3>
            <p>12</p>
          </Card>
        </div>

        {/* TABLE WITHOUT PAGINATION */}
        <Card className="reports-table-card">
          <Table columns={columns} dataSource={filteredData} pagination={false} bordered />
        </Card>
      </div>

      <Modal open={!!viewModalData} onCancel={() => setViewModalData(null)} footer={null} title="Report Details">
        {viewModalData && (
          <>
            <p><b>Name:</b> {viewModalData.name}</p>
            <p><b>Category:</b> {viewModalData.category}</p>
            <p><b>Generated By:</b> {viewModalData.generatedBy}</p>
            <p><b>Date:</b> {viewModalData.date}</p>
          </>
        )}
      </Modal>
    </div>
  );
};

export default Reports;
